[features]
seeds = false
[programs.devnet]
crowdfunding_platform = "BwRQnxwjCkVk5uFNLVgacEBXgVreQL79KmtzrHhLvSfv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
